### ISSUE TITLE
Plugin causing module resolution problems

### ISSUE THREAD

**Issue by cowwoc** [mdreizin/gulp-webpack-build#4]
If you take the testcase at https://github.com/webpack/webpack/issues/747 and run webpack from command-line, the `q.js` resolution problem will go away.

**Comment by mdreizin** [comment]
@cowwoc I have just run `webpack --config webpack.config.js` and I have got:

```
ash: 861ec26824f86f50dc52
Version: webpack 1.5.3
Time: 17ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/main/webapp/com/realestate/frontend/page/Index.js in /Users/mdreizin/Developer/src/github.com/webpack-q.js/gulp
```

and I have got via `gulp build`:

```
[22:25:47] Using gulpfile ~/Developer/src/github.com/webpack-q.js/Gulpfile.js
[22:25:47] Starting 'package'...
[22:25:47] Compiling webpack config ~/Developer/src/github.com/webpack-q.js/gulp/webpack.config.js
[22:25:47]
Time: 40ms
   Asset  Size  Chunks             Chunk Names
Index.js  1693       0  [emitted]  Index

ERROR in ./src/main/webapp/com/realestate/frontend/page/Index.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/mdreizin/Developer/src/github.com/webpack-q.js/target/webjars/META-INF/resources/webjars/q/1.1.2/q.js in /Users/mdreizin/Developer/src/github.com/webpack-q.js/src/main/webapp/com/realestate/frontend/page
 @ ./src/main/webapp/com/realestate/frontend/page/Index.js 2:8-31

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Webpack cannot compile config
    at DestroyableTransform.<anonymous> (/Users/mdreizin/Developer/src/github.com/webpack-q.js/node_modules/gulp-webpack-build/index.js:170:23)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at /Users/mdreizin/Developer/src/github.com/webpack-q.js/node_modules/gulp-webpack-build/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:442:13)
```

**Comment by cowwoc** [comment]
What is your working directory for each case? `webpack.config.js` is located in `/gulp`, are you running from inside there or from the root directory?

**Comment by cowwoc** [comment]
@mdreizin I just cleaned up the testcase. You should now be able to run `webpack --config webpack.config.js` and `gulp build` from the root directory.

In the former case you should get:
```
Hash: b5a7fe00410b19a46730
Version: webpack 1.5.3
Time: 169ms
   Asset   Size  Chunks             Chunk Names
Index.js  67916       0  [emitted]  Index
   [0] ./src/main/webapp/Index.js 62 {0} [built]
   [1] ./target/webjars/META-INF/resources/webjars/q/1.1.2/q.js 58882 {0} [built
]
    + 3 hidden modules
```

In the latter case you should get:

```
[16:55:44] Using gulpfile ~\Documents\webpack-q.js\Gulpfile.js
[16:55:44] Starting 'package'...
[16:55:44] Compiling webpack config ~\Documents\webpack-q.js\webpack.config.js
[16:55:44]
Time: 147ms
   Asset   Size  Chunks             Chunk Names
Index.js  66710       0  [emitted]  Index

ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\Gili\Documents\webpack-q.js\node_modules\webpack\node_modules\node-libs-browser\node_modules\process\browser.js/browser.js in C:\Users\Gili\Documents\webpack-q.js\node_modules\webpack\node_modules\node-libs-browser\node_modules\timers-browserify
 @ (webpack)/~/node-libs-browser/~/timers-browserify/main.js 1:15-44

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Webpack cannot compile config
    at DestroyableTransform.<anonymous> (C:\Users\Gili\Documents\webpack-q.js\node_modules\gulp-webpack-build\index.js:170:23)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at C:\Users\Gili\Documents\webpack-q.js\node_modules\gulp-webpack-build\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:442:13)
```

Let me know if you can reproduce the problem now.

**Comment by mdreizin** [comment]
@cowwoc I used `gulp` directory.

**Comment by cowwoc** [comment]
@mdreizin How about the updated testcase I referred to above? https://github.com/cowwoc/webpack-q.js/tree/3e2da049d012c92e9bde81b93534a7fa0a08c7b2

**Comment by mdreizin** [comment]
@cowwoc I have just updated and unfortunately I can't reproduce this bug :(

**Comment by cowwoc** [comment]
@mdreizin Can you please send me with a **complete** execution log? Here is what I am looking for:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Gili>cd Documents
C:\Users\Gili\Documents>cd webpack-q.js
C:\Users\Gili\Documents\webpack-q.js>webpack --config webpack.config.js
Hash: b5a7fe00410b19a46730
Version: webpack 1.5.3
Time: 157ms
   Asset   Size  Chunks             Chunk Names
Index.js  67916       0  [emitted]  Index
   [0] ./src/main/webapp/Index.js 62 {0} [built]
   [1] ./target/webjars/META-INF/resources/webjars/q/1.1.2/q.js 58882 {0} [built
]
    + 3 hidden modules

C:\Users\Gili\Documents\webpack-q.js>gulp build
[17:19:08] Using gulpfile ~\Documents\webpack-q.js\Gulpfile.js
[17:19:08] Starting 'package'...
[17:19:09] Compiling webpack config ~\Documents\webpack-q.js\webpack.config.js
[17:19:09]
Time: 138ms
   Asset   Size  Chunks             Chunk Names
Index.js  66710       0  [emitted]  Index

ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\Gili\Documents\webpack-q.js\node_modules\webpack\node_modules\node-libs-browser\node_modules\process\browser.js/browser.js in C:\Users\Gili\Documents\webpack-q.js\node_modules\webpack\node_modules\node-libs-browser\node_modules\timers-browserify
 @ (webpack)/~/node-libs-browser/~/timers-browserify/main.js 1:15-44

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Webpack cannot compile config
    at DestroyableTransform.<anonymous> (C:\Users\Gili\Documents\webpack-q.js\node_modules\gulp-webpack-build\index.js:170:23)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at C:\Users\Gili\Documents\webpack-q.js\node_modules\gulp-webpack-build\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:442:13)
```

I am running under Windows 7, 64-bit, node v0.10.36, npm 1.4.28.

Please provide me with the equivalent information for your end. Thanks in advance.

**Comment by mdreizin** [comment]
@cowwoc Here is my execution log:

```os x 10.10.2```

```
node -v && npm -v

v0.10.36
2.3.0
```

```
Marat-Dreizins-MacBook-Pro-Fitbit:webpack-q.js mdreizin$ webpack --config webpack.config.js
Hash: 8ee478f0168bba67d98d
Version: webpack 1.5.3
Time: 36ms
   Asset   Size  Chunks             Chunk Names
Index.js  62235       0  [emitted]  Index
   [0] ./src/main/webapp/Index.js 62 {0} [built]
   [1] ./target/webjars/META-INF/resources/webjars/q/1.1.2/q.js 58882 {0} [built]
Marat-Dreizins-MacBook-Pro-Fitbit:webpack-q.js mdreizin$ gulp build
[09:51:44] Using gulpfile ~/Developer/src/github.com/webpack-q.js/Gulpfile.js
[09:51:44] Starting 'package'...
[09:51:44] Compiling webpack config ~/Developer/src/github.com/webpack-q.js/webpack.config.js
[09:51:44]
Time: 34ms
   Asset   Size  Chunks             Chunk Names
Index.js  62235       0  [emitted]  Index
[09:51:44] Finished 'package' after 68 ms
[09:51:44] Starting 'build'...
[09:51:44] Finished 'build' after 6.05 μs
```

```window 7```

```
node -v && npm -v

v0.10.36
1.4.28
```

```
C:\Users\IEUser\Developer\webpack-q.js>webpack --config webpack.config.js
Hash: 23d306333f581ace5160
Version: webpack 1.5.3
Time: 93ms
   Asset   Size  Chunks             Chunk Names
Index.js  69854       0  [emitted]  Index
   [0] ./src/main/webapp/Index.js 63 {0} [built]
   [1] ./target/webjars/META-INF/resources/webjars/q/1.1.2/q.js 60819 {0} [built]
    + 3 hidden modules

C:\Users\IEUser\Developer\webpack-q.js>gulp build
[11:22:52] Using gulpfile ~\Developer\webpack-q.js\Gulpfile.js
[11:22:52] Starting 'package'...
[11:22:52] Compiling webpack config ~\Developer\webpack-q.js\webpack.config.js
[11:22:52]
Time: 93ms
   Asset   Size  Chunks             Chunk Names
Index.js  68648       0  [emitted]  Index

ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\IEUser\Developer\webpack-q.js\node_modules\webpack\node_modules\node-libs-browser\no
de_modules\process\browser.js/browser.js in C:\Users\IEUser\Developer\webpack-q.js\node_modules\webpack\node_modules\node-libs-browser\node_modules\timers-
browserify
 @ (webpack)/~/node-libs-browser/~/timers-browserify/main.js 1:15-44

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Webpack cannot compile config
    at DestroyableTransform.<anonymous> (C:\Users\IEUser\Developer\webpack-q.js\node_modules\gulp-webpack-build\index.js:162:23)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at C:\Users\IEUser\Developer\webpack-q.js\node_modules\gulp-webpack-build\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:96
5:16
    at process._tickCallback (node.js:442:13)
```

It looks like that is `webpack` windows-specific issue.

**Comment by mdreizin** [comment]
@cowwoc Please update to v0.2.9

**Comment by cowwoc** [comment]
@mdreizin Confirmed this is fixed. Thank you!

**Comment by cowwoc** [comment]
Out of curiosity, do you know why this bug was platform-specific?
